# Generated by Django 6.0.3 on 2026-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_region_client_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('increase', 'Miqdorni oshirish'), ('decrease', 'Miqdorni kamaytirish'), ('price_change', 'Narxni o‘zgartirish'), ('correction', 'To‘liq tuzatish'), ('return', 'Sotuv qaytarish')], max_length=20),
        ),
    ]
