# Generated by Django 6.0.3 on 2026-05-04 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stockbatch_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('product_create', "Mahsulot qo'shildi"), ('product_update', 'Mahsulot yangilandi'), ('product_delete', "Mahsulot o'chirildi"), ('stock_add', 'Stock kirim qilindi'), ('stock_adjust', 'Stock tuzatildi'), ('stock_delete', "Batch o'chirildi"), ('sale', 'Sotuv amalga oshirildi'), ('sale_return', 'Sotuv qaytarildi'), ('payment', "To'lov qabul qilindi"), ('payment_refund', "To'lov qaytarildi"), ('client_create', "Mijoz qo'shildi"), ('client_update', 'Mijoz yangilandi'), ('client_delete', "Mijoz o'chirildi")], max_length=20, verbose_name='Harakat turi'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='products_ac_created_bbe500_idx'),
        ),
    ]
