# Generated by Django 6.0.3 on 2026-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'dashboard_summary_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('month', models.DateField(primary_key=True, serialize=False)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'monthly_summary_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopProductSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=100)),
                ('total_sold', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'top_products_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('week_start', models.DateField(primary_key=True, serialize=False)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'weekly_summary_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearlySummary',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'yearly_summary_mv',
                'managed': False,
            },
        ),
    ]
